version: '3.8'
services:
  code-server:
    build:
      context: ./docker
      dockerfile: Dockerfile
    env_file:
      - ./docker/.env
    ports:
      - "8443:8443"
    volumes:
      - ./docker:/workspace
      - ./data:/data
      - code-server-config:/home/coder/.config/code-server
      - code-server-data:/home/coder/.local/share/code-server
    command: ["/usr/bin/code-server", "/data", "--bind-addr", "0.0.0.0:8443", "--auth", "password", "--cert", "/home/coder/.config/code-server/certs/code-server.crt", "--cert-key", "/home/coder/.config/code-server/certs/code-server.key"]
    restart: unless-stopped
volumes:
  code-server-config:
  code-server-data:
