#!/bin/bash
set -e

# This script now only installs extensions since we use Let's Encrypt certificates
# The certificates are generated by certbot and mounted into the container

echo "Installing recommended VS Code extensions..."

# Install recommended extensions if not already installed
EXT_LIST="jebbs.plantuml asciidoctor.asciidoctor-vscode"
for ext in $EXT_LIST; do
  if ! /usr/bin/code-server --list-extensions | grep -q "$ext"; then
    echo "Installing extension: $ext"
    /usr/bin/code-server --install-extension "$ext"
  else
    echo "Extension already installed: $ext"
  fi
done

echo "Extension installation complete."
echo "Using Let's Encrypt certificates from /etc/letsencrypt/live/\${CERT_NAME}/"
