#!/bin/bash
set -e

# This script now only installs extensions since we use Let's Encrypt certificates
# The certificates are generated by certbot and mounted into the container

echo "Installing recommended VS Code extensions..."



# Install recommended extensions if available on Open VSX and not already installed
cat /tmp/extensions.txt | while read ext; do
  # Skip empty lines
  [ -z "$ext" ] && continue
  publisher="${ext%%.*}"
  name="${ext#*.}"
  # Check if extension is available on Open VSX using direct API endpoint
  status=$(curl -s -o /dev/null -w "%{http_code}" "https://open-vsx.org/api/$publisher/$name/latest")
  if [ "$status" = "200" ]; then
    if ! /usr/bin/code-server --list-extensions | grep -q "$ext"; then
      echo "Installing extension: $ext"
      /usr/bin/code-server --install-extension "$ext"
    else
      echo "Extension already installed: $ext"
    fi
  else
    echo "Extension $ext not found on Open VSX, skipping."
  fi
done

echo "Extension installation complete."
echo "Using Let's Encrypt certificates from /etc/letsencrypt/live/\${CERT_NAME}/"
