version: '3.8'
services:
  coredns:
    image: coredns/coredns:latest
    command: -conf /etc/coredns/Corefile
    volumes:
      - ./docker-coredns/Corefile:/etc/coredns/Corefile:ro
      - ./docker-coredns/hosts:/etc/coredns/hosts:ro
    networks:
      internal:
        ipv4_address: 172.20.0.10
    restart: unless-stopped

  code-server:
    build:
      context: ./docker-vsc
      dockerfile: Dockerfile
    env_file:
      - ./docker-vsc/.env
    environment:
      - CERT_HOSTNAMES=${CERT_HOSTNAMES:-vscode.vsagcrd.org localhost 127.0.0.1}
      - VSCODE_CERT_NAME=${VSCODE_CERT_NAME:-vscode}
    volumes:
      - ../:/workspace
      - ../data:/data
      - code-server-config:/home/coder/.config/code-server
      - code-server-data:/home/coder/.local/share/code-server
      - code-server-code:/home/coder/code
      - cert-output:/etc/letsencrypt/live:ro
    command: ["/usr/bin/code-server", "/home/coder/code", "--bind-addr", "0.0.0.0:8443", "--auth", "password", "--cert", "/etc/letsencrypt/live/${VSCODE_CERT_NAME:-vscode}/fullchain.pem", "--cert-key", "/etc/letsencrypt/live/${VSCODE_CERT_NAME:-vscode}/privkey.pem"]
    restart: unless-stopped
    dns:
      - 172.20.0.10
    networks:
      internal:
        ipv4_address: 172.20.0.12
        aliases:
          - vscode.vsagcrd.org
    depends_on:
      - coredns

  cert-generator:
    build:
      context: ./docker-certbot
      dockerfile: Dockerfile
    env_file:
      - ./docker-certbot/.env
    volumes:
      - cert-output:/etc/letsencrypt/live
    profiles:
      - tools
    dns:
      - 172.20.0.10
    networks:
      internal:
        ipv4_address: 172.20.0.13
        aliases:
          - certbot.vsagcrd.org
    depends_on:
      - coredns

  proxy:
    build:
      context: ./docker-proxy
      dockerfile: Dockerfile
    env_file:
      - ./docker-proxy/.env
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"
    volumes:
      - cert-output:/etc/nginx/certs:ro
    depends_on:
      - code-server
      - coredns
    restart: unless-stopped
    dns:
      - 172.20.0.10
    networks:
      internal:
        ipv4_address: 172.20.0.11
        aliases:
          - proxy.vsagcrd.org

volumes:
  code-server-config:
  code-server-data:
  code-server-code:
  cert-output:

networks:
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
